version: 2.1

parameters:
  image-go:
    type: string
    default: "cimg/go:1.19"
  workingdir:
    type: string
    default: "~/cicd-git-practice/app/app/"

commands:
  golangci-lint:
    parameters:
      version:
        description: version of golangci-lint
        type: string
        default: '1.21.0'
      flags:
        description: command line flags for golangci-lint run
        type: string
        default: ''
    steps:
      - run:
          name: Download golangci-lint
          command: |
            curl -sL https://github.com/golangci/golangci-lint/releases/download/v<< parameters.version >>/golangci-lint-<< parameters.version >>-linux-amd64.tar.gz | tar xz
      - run:
          name: Run golangci-lint checks
          command: |
            golangci-lint-<< parameters.version >>-linux-amd64/golangci-lint run << parameters.flags >>

orbs:
  go: circleci/go@1.7.1

jobs:
  lint:
    working_directory: << pipeline.parameters.workingdir >>
    docker:
      - image: << pipeline.parameters.image-go >>
    steps:
      - checkout
      - go/mod-download
      - golangci-lint

  test:
    working_directory: << pipeline.parameters.workingdir >>
    docker:
      - image: << pipeline.parameters.image-go >>
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: pg
          POSTGRES_DB: terminal_dev
          POSTGRES_HOST: db
          POSTGRES_PASSWORD: pass
          POSTGRES_PORT: 5432
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  # deploy: 


workflows:
  lint-test-deploy:
    when:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - test
      # - deploy

  test:
    when:
      not:
        or:
          - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - test