version: 2.1

parameters:
  image-go:
    type: string
    default: "cimg/go:1.19"
  workingdir:
    type: string
    default: "~/cicd-git-practice/app/app/"

orbs:
  go: circleci/go@1.7.1
  golangci-lint: neilisaac/golangci-lint@0.0.1

jobs:
  lint:
    working_directory: "~/cicd-git-practice/app/app"
    docker:
      - image: << pipeline.parameters.image-go >>
    steps:
      - checkout
      - go/mod-download
      - golangci-lint/lint

  test:
    working_directory: "~/cicd-git-practice/app/app"
    docker:
      - image: << pipeline.parameters.image-go >>
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: pg
          POSTGRES_DB: terminal_dev
          POSTGRES_HOST: db
          POSTGRES_PASSWORD: pass
          POSTGRES_PORT: 5432
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  # deploy: 


workflows:
  lint-test-deploy:
    when:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - test
      # - deploy

  test:
    when:
      not:
        or:
          - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - test