version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  test:
    working_directory: ~/cicd-git-practice
    docker:
      - image: cimg/go:1.19
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: pg
          POSTGRES_DB: terminal_dev
          POSTGRES_HOST: db
          POSTGRES_PASSWORD: pass
          POSTGRES_PORT: 5432
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  build-with-docker:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main