version: 2.1

parameters:
  image-go:
    type: string
    default: "cimg/go:1.19"
  workingdir:
    type: string
    default: "~/cicd-git-practice/"

commands:
  lint:
    steps:
      - run:
          name: run lint check
          command:
            test -z $(gofmt -l .)

orbs:
  go: circleci/go@1.7.1
  node: circleci/node@5.0.2
  pulumi: pulumi/pulumi@2.1.0

jobs:
  lint:
    working_directory: << pipeline.parameters.workingdir >>
    docker:
      - image: << pipeline.parameters.image-go >>
    steps:
      - checkout
      - go/mod-download
      - lint

  test:
    working_directory: << pipeline.parameters.workingdir >>
    docker:
      - image: << pipeline.parameters.image-go >>
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: pg
          POSTGRES_DB: terminal_dev
          POSTGRES_HOST: db
          POSTGRES_PASSWORD: pass
          POSTGRES_PORT: 5432
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  update-stack: 
    working_directory: << pipeline.parameters.workingdir >>
    docker:
      - image: cimg/node:18.4.0
    parameters:
      stack:
        type: string
    steps: 
      - checkout
      - node/install-packages:
          app-dir: ./infra/
          pkg-manager: yarn
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - pulumi/login
      - pulumi/update:
          working_directory: ./infra/
          stack: << parameters.stack >>


workflows:
  lint-test-deploy:
    when:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - test
      - update-stack:
          requires:
            - lint
            - test
          stack: phatnm96/infra/dev

  test:
    when:
      not:
        or:
          - equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - lint
      - test