version: '3.8'

services:
  terminal:
    depends_on: 
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: git-practice
    hostname: git-practice
    ports:
      - 80:8080
    deploy:
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres:14.5-alpine
    container_name: git-practice-data
    hostname: db
    env_file:
      - .env.development.local
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: